[package]
name = "iroha"
version = "0.1.0"
authors = ["i1i1 <vanyarybin1@live.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana_rbpf = "0.2.14"
color-eyre = "0.5.11"
